/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmRegister: typeof import('./src/components/Header/components/emRegister.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Login: typeof import('./src/components/Header/components/login.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    PhoneRegister: typeof import('./src/components/Header/components/phoneRegister.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
